[build]
publish = "public"
#command = "hugo --gc --minify"
command = "hugo --gc --minify --baseURL https://docs.neuralvibes.com/"

[build.environment]
  HUGO_VERSION = "0.88.1"
  NODE_VERSION = "16.9.1"
  NPM_VERSION = "7.21.1"

[context.production]
  command = "hugo -b $URL --gc --minify && npm run build:functions"

[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL --gc --minify"

[context.branch-deploy]
  command = "hugo -b $DEPLOY_PRIME_URL --gc --minify"

[context.branch-deploy.environment]
HUGO_VERSION = "0.87.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

